name: Send Email on Push

on:
  push:
    branches:
      - '*'


  
jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send email
        env: 
          EMAIL_ADDRESS: ${{ secrets.EMAIL }}
        run: |
          echo $(env | grep TERM_PROGRAM)
#         run: |
#           SUBJECT="github action was used"
#           BODY="github action was used"
#           echo -e "Subject:$SUBJECT\n$BODY" | mail -s "$SUBJECT" "$EMAIL_ADDRESS"
